# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'infer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binfer.proto\x12\x04\x65\x64ge\"s\n\x0cImageRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x11\n\timage_b64\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x12\x0b\n\x03seq\x18\x06 \x01(\x03\"x\n\tDetection\x12\x10\n\x08\x63lass_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0c\n\x04xmin\x18\x03 \x01(\x02\x12\x0c\n\x04ymin\x18\x04 \x01(\x02\x12\x0c\n\x04xmax\x18\x05 \x01(\x02\x12\x0c\n\x04ymax\x18\x06 \x01(\x02\x12\x12\n\nclass_name\x18\x07 \x01(\t\"\x82\x01\n\x11\x44\x65tectionResponse\x12\x0e\n\x06source\x18\x01 \x01(\t\x12#\n\ndetections\x18\x02 \x03(\x0b\x32\x0f.edge.Detection\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x0b\n\x03seq\x18\x04 \x01(\x03\x12\x15\n\rprocessing_ms\x18\x05 \x01(\x03\x32\x46\n\tInference\x12\x39\n\x06Stream\x12\x12.edge.ImageRequest\x1a\x17.edge.DetectionResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=21
  _globals['_IMAGEREQUEST']._serialized_end=136
  _globals['_DETECTION']._serialized_start=138
  _globals['_DETECTION']._serialized_end=258
  _globals['_DETECTIONRESPONSE']._serialized_start=261
  _globals['_DETECTIONRESPONSE']._serialized_end=391
  _globals['_INFERENCE']._serialized_start=393
  _globals['_INFERENCE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
